import {FormEvent,useEffect,useMemo,useState} from 'react';
import {BarChart3,Bird,Boxes,CalendarDays,ClipboardList,Egg,FileText,HeartPulse,Home,LogOut,Menu,PackagePlus,Settings,ShoppingCart,Syringe,Truck,Users,WalletCards,Wrench,X} from 'lucide-react';
import './styles.css';

type Data=Record<string,any>;
type Extra={key:string;label:string;type?:string};
type Module={key:string;title:string;icon:any;hint:string;quantity?:string;amount?:string;extras:Extra[]};
const API=(import.meta.env.VITE_API_URL||'http://localhost:3333/api').replace(/\/$/,'');
const modules:Module[]=[
 {key:'aviarios',title:'Aviários',icon:Home,hint:'Estruturas, capacidade e localização',quantity:'Capacidade',extras:[{key:'code',label:'Código'},{key:'type',label:'Sistema de criação'},{key:'location',label:'Localização'}]},
 {key:'lotes',title:'Lotes de aves',icon:Bird,hint:'Plantel, linhagem, origem e ciclo',quantity:'Aves atuais',extras:[{key:'house',label:'Aviário'},{key:'breed',label:'Linhagem'},{key:'source',label:'Origem'},{key:'initialQuantity',label:'Quantidade inicial',type:'number'}]},
 {key:'ficha-diaria',title:'Ficha diária',icon:ClipboardList,hint:'Ração, água, mortalidade e ambiência',quantity:'Aves no fim',extras:[{key:'lot',label:'Lote'},{key:'feedKg',label:'Ração (kg)',type:'number'},{key:'waterLiters',label:'Água (L)',type:'number'},{key:'mortality',label:'Mortalidade',type:'number'},{key:'temperature',label:'Temperatura',type:'number'},{key:'humidity',label:'Umidade',type:'number'}]},
 {key:'coleta-ovos',title:'Coleta de ovos',icon:Egg,hint:'Produção e classificação por tamanho',quantity:'Ovos totais',extras:[{key:'lot',label:'Lote'},{key:'saleableEggs',label:'Comercializáveis',type:'number'},{key:'jumbo',label:'Jumbo',type:'number'},{key:'large',label:'Grandes',type:'number'},{key:'medium',label:'Médios',type:'number'},{key:'small',label:'Pequenos',type:'number'},{key:'broken',label:'Trincados',type:'number'},{key:'dirty',label:'Sujos',type:'number'}]},
 {key:'vacinas',title:'Catálogo de vacinas',icon:Syringe,hint:'Produtos, doses e carências',extras:[{key:'manufacturer',label:'Fabricante'},{key:'dose',label:'Dose padrão'},{key:'intervalDays',label:'Intervalo (dias)',type:'number'},{key:'withdrawalDays',label:'Carência (dias)',type:'number'}]},
 {key:'vacinacoes',title:'Vacinações',icon:Syringe,hint:'Agenda, aplicações e reforços',quantity:'Aves atendidas',extras:[{key:'lot',label:'Lote'},{key:'vaccine',label:'Vacina'},{key:'dose',label:'Dose'},{key:'route',label:'Via'},{key:'batchNumber',label:'Lote do produto'},{key:'responsible',label:'Responsável'}]},
 {key:'sanidade',title:'Sanidade',icon:HeartPulse,hint:'Tratamentos, doenças, exames e carência',quantity:'Aves atendidas',amount:'Custo',extras:[{key:'lot',label:'Lote'},{key:'eventType',label:'Tipo de ocorrência'},{key:'product',label:'Produto'},{key:'diagnosis',label:'Diagnóstico'},{key:'dosage',label:'Dosagem'},{key:'withdrawalUntil',label:'Carência até',type:'date'},{key:'responsible',label:'Responsável'}]},
 {key:'estoque',title:'Estoque',icon:Boxes,hint:'Ração, medicamentos, vacinas e embalagens',quantity:'Saldo atual',amount:'Custo unitário',extras:[{key:'category',label:'Categoria'},{key:'unit',label:'Unidade'},{key:'minimumStock',label:'Estoque mínimo',type:'number'},{key:'batchNumber',label:'Lote'},{key:'expiresAt',label:'Validade',type:'date'},{key:'location',label:'Localização'}]},
 {key:'movimentacoes',title:'Movimentações',icon:PackagePlus,hint:'Entradas, saídas e ajustes',quantity:'Quantidade',amount:'Custo unitário',extras:[{key:'item',label:'Item'},{key:'movementType',label:'Tipo'},{key:'reason',label:'Motivo'},{key:'document',label:'Documento'}]},
 {key:'compras',title:'Compras',icon:ShoppingCart,hint:'Pedidos e recebimentos',amount:'Valor total',extras:[{key:'supplier',label:'Fornecedor'},{key:'invoice',label:'Nota fiscal'},{key:'dueDate',label:'Vencimento',type:'date'},{key:'receivedAt',label:'Recebido em',type:'date'}]},
 {key:'fornecedores',title:'Fornecedores',icon:Truck,hint:'Parceiros e condições comerciais',extras:[{key:'document',label:'CNPJ/CPF'},{key:'category',label:'Categoria'},{key:'contact',label:'Contato'},{key:'phone',label:'Telefone'},{key:'email',label:'E-mail'},{key:'city',label:'Cidade/UF'}]},
 {key:'clientes',title:'Clientes',icon:Users,hint:'Cadastro e histórico comercial',extras:[{key:'document',label:'CNPJ/CPF'},{key:'phone',label:'Telefone'},{key:'email',label:'E-mail'},{key:'city',label:'Cidade/UF'},{key:'priceTable',label:'Tabela de preços'}]},
 {key:'vendas',title:'Vendas e entregas',icon:ShoppingCart,hint:'Pedidos, pagamentos e rastreabilidade',quantity:'Quantidade',amount:'Valor total',extras:[{key:'customer',label:'Cliente'},{key:'product',label:'Produto'},{key:'eggGrade',label:'Classificação'},{key:'unit',label:'Unidade'},{key:'paymentMethod',label:'Forma de pagamento'},{key:'deliveryAddress',label:'Endereço de entrega'},{key:'sourceLot',label:'Lote de origem'}]},
 {key:'gastos',title:'Gastos e contas',icon:WalletCards,hint:'Despesas, vencimentos e pagamentos',amount:'Valor',extras:[{key:'category',label:'Categoria'},{key:'supplier',label:'Fornecedor'},{key:'dueDate',label:'Vencimento',type:'date'},{key:'paymentMethod',label:'Forma de pagamento'},{key:'document',label:'Documento'}]},
 {key:'tarefas',title:'Tarefas',icon:CalendarDays,hint:'Rotinas, responsáveis e recorrências',extras:[{key:'category',label:'Categoria'},{key:'priority',label:'Prioridade'},{key:'assignedTo',label:'Responsável'},{key:'recurring',label:'Recorrência'}]},
 {key:'manutencoes',title:'Manutenções',icon:Wrench,hint:'Equipamentos, instalações e custos',amount:'Custo',extras:[{key:'equipment',label:'Equipamento'},{key:'category',label:'Categoria'},{key:'supplier',label:'Fornecedor'},{key:'responsible',label:'Responsável'}]},
 {key:'visitantes',title:'Biossegurança',icon:Users,hint:'Visitantes, veículos e autorizações',extras:[{key:'company',label:'Empresa'},{key:'purpose',label:'Finalidade'},{key:'document',label:'Documento'},{key:'vehiclePlate',label:'Placa do veículo'},{key:'authorizedBy',label:'Autorizado por'}]},
 {key:'ambiencia',title:'Ambiência e água',icon:BarChart3,hint:'Temperatura, umidade, amônia e água',extras:[{key:'house',label:'Aviário'},{key:'temperature',label:'Temperatura',type:'number'},{key:'humidity',label:'Umidade',type:'number'},{key:'ammoniaPpm',label:'Amônia (ppm)',type:'number'},{key:'waterPh',label:'pH da água',type:'number'},{key:'chlorine',label:'Cloro (ppm)',type:'number'}]},
 {key:'documentos',title:'Documentos',icon:FileText,hint:'Laudos, notas, POPs e certificados',extras:[{key:'category',label:'Categoria'},{key:'url',label:'Link do arquivo'},{key:'expiresAt',label:'Validade',type:'date'}]}
];
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:any)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
async function api(path:string,token?:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message||'Falha na operação');return response.status===204?null:response.json()}
function Login({onLogin}:{onLogin:(v:any)=>void}){const[email,setEmail]=useState('admin@granjamafaldo.com.br'),[password,setPassword]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{onLogin(await api('/auth/login',undefined,{method:'POST',body:JSON.stringify({email,password})}))}catch(x:any){setError(x.message)}}return <main className="login"><section className="login-art"><img src="/brand-wordmark.svg"/><h1>Gestão completa da produção ao resultado.</h1><p>Ovos, aves, sanidade, estoque, vendas e finanças em um único sistema.</p></section><form className="login-card" onSubmit={submit}><h2>Acessar a plataforma</h2>{error&&<div className="error">{error}</div>}<label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Entrar</button></form></main>}
function Dashboard({token}:{token:string}){const[d,setD]=useState<any>();useEffect(()=>{api('/dashboard',token).then(setD)},[token]);if(!d)return <div className="empty">Carregando painel...</div>;const k=d.kpis;return <><header className="hero"><div><small>GRANJA MAFALDO</small><h1>Visão geral da operação</h1><p>Acompanhe os indicadores mais importantes do dia.</p></div><Egg size={64}/></header><section className="kpis">{[['Aves ativas',k.birds],['Ovos hoje',k.totalEggs],['Taxa de postura',`${k.layRate}%`],['Ração hoje',`${k.feedKg} kg`],['Receitas do mês',money(k.revenue)],['Resultado do mês',money(k.revenue-k.expenses)]].map(([a,b])=><article key={a}><span>{a}</span><strong>{b}</strong></article>)}</section><section className="dashboard-grid"><Panel title="Lotes ativos" rows={d.lots}/><Panel title="Estoque prioritário" rows={d.stock}/><Panel title="Próximas vacinações" rows={d.vaccines}/><Panel title="Tarefas abertas" rows={d.tasks}/></section></>}
function Panel({title,rows}:{title:string;rows:any[]}){return <article className="panel"><h3>{title}</h3>{rows.length?rows.map(x=><div className="panel-row" key={x.id}><span>{x.title}<small>{x.status||date(x.date)}</small></span><b>{x.quantity??date(x.date)}</b></div>):<p>Nenhum registro.</p>}</article>}
function ModulePage({module,token}:{module:Module;token:string}){const[rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>({data:{}}),[error,setError]=useState('');const load=()=>api(`/data/${module.key}`,token).then(setRows).catch((e:any)=>setError(e.message));useEffect(load,[module.key]);async function save(e:FormEvent){e.preventDefault();try{await api(`/data/${module.key}`,token,{method:'POST',body:JSON.stringify(form)});setOpen(false);setForm({data:{}});load()}catch(x:any){setError(x.message)}}function extra(key:string,value:string){setForm((f:any)=>({...f,data:{...f.data,[key]:value}}))}return <><header className="page-head"><div><module.icon/><span><h1>{module.title}</h1><p>{module.hint}</p></span></div><button onClick={()=>setOpen(true)}>+ Novo registro</button></header>{error&&<div className="error">{error}</div>}<section className="table"><div className="table-header"><b>Registro</b><b>Data</b><b>Status</b><b>{module.quantity||module.amount||'Detalhes'}</b></div>{rows.map(r=><div className="table-row" key={r.id}><span><strong>{r.title}</strong><small>{Object.values(r.data||{}).filter(Boolean).slice(0,2).join(' • ')}</small></span><span>{date(r.date)}</span><span className="badge">{r.status||'—'}</span><b>{module.amount?money(r.amount):r.quantity??'—'}</b></div>)}{!rows.length&&<div className="empty">Nenhum registro cadastrado.</div>}</section>{open&&<div className="modal-bg"><form className="modal" onSubmit={save}><header><h2>Novo registro — {module.title}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="fields"><label>Título<input required onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Data<input type="date" onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Status<input placeholder="ACTIVE, PENDING, PAID..." onChange={e=>setForm({...form,status:e.target.value})}/></label>{module.quantity&&<label>{module.quantity}<input type="number" step="any" onChange={e=>setForm({...form,quantity:e.target.value})}/></label>}{module.amount&&<label>{module.amount}<input type="number" step="any" onChange={e=>setForm({...form,amount:e.target.value})}/></label>}{module.extras.map(f=><label key={f.key}>{f.label}<input type={f.type||'text'} step={f.type==='number'?'any':undefined} onChange={e=>extra(f.key,e.target.value)}/></label>)}<label className="full">Observações<textarea onChange={e=>extra('notes',e.target.value)}/></label></div><footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button>Salvar</button></footer></form></div>}</>}
export default function App(){const[session,setSession]=useState<any>(()=>JSON.parse(localStorage.getItem('gm-session')||'null')),[active,setActive]=useState('dashboard'),[menu,setMenu]=useState(false);const current=useMemo(()=>modules.find(m=>m.key===active),[active]);function login(v:any){localStorage.setItem('gm-session',JSON.stringify(v));setSession(v)}function logout(){localStorage.removeItem('gm-session');setSession(null)}if(!session)return <Login onLogin={login}/>;return <div className="app"><aside className={menu?'open':''}><div className="brand"><img src="/brand-wordmark.svg"/><button onClick={()=>setMenu(false)}><X/></button></div><nav><button className={active==='dashboard'?'active':''} onClick={()=>{setActive('dashboard');setMenu(false)}}><BarChart3/>Visão geral</button>{modules.map(m=><button key={m.key} className={active===m.key?'active':''} onClick={()=>{setActive(m.key);setMenu(false)}}><m.icon/>{m.title}</button>)}</nav><button className="logout" onClick={logout}><LogOut/>Sair</button></aside><section className="content"><header className="mobile"><button onClick={()=>setMenu(true)}><Menu/></button><img src="/brand-icon.svg"/><b>{session.farm.name}</b></header><main>{active==='dashboard'?<Dashboard token={session.token}/>:current&&<ModulePage module={current} token={session.token}/>}</main></section></div>}
